# Generated by Django 5.1.5 on 2025-03-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_restaurant_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='menuitemcategory',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='menumodifier',
            name='menu_item',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='is_open',
            new_name='is_maintained',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='MenuModifier',
        ),
    ]
