# Generated by Django 5.1.5 on 2025-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_restaurant_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.DeleteModel(
            name='RestaurantCategory',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('fine_dining', 'Fine Dining'), ('vegan', 'Vegan'), ('seafood', 'Seafood'), ('fast_food', 'Fast Food'), ('drinks_and_beverages', 'Drinks & Beverages'), ('desserts', 'Desserts'), ('bakery', 'Bakery'), ('café', 'Café'), ('halal', 'Halal'), ('bbq_and_grills', 'BBQ & Grills'), ('other', 'Other')], default='', max_length=25),
        ),
    ]
