# Generated by Django 5.1.5 on 2025-03-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Fine Dining', 'Fine Dining'), ('Vegan', 'Vegan'), ('Seafood', 'Seafood'), ('Fast Food', 'Fast Food'), ('Drinks & Beverages', 'Drink And Beverages'), ('Desserts', 'Desserts'), ('Café', 'Cafe'), ('Halal', 'Halal'), ('BBQ & Grills', 'Bbq And Grills'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
