# Generated by Django 5.1.5 on 2025-03-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[(None, '----------'), ('fine_dining', 'Fine Dining'), ('vegan', 'Vegan'), ('seafood', 'Seafood'), ('fast_food', 'Fast Food'), ('drink_and_beverages', 'Drinks & Beverages'), ('desserts', 'Desserts'), ('cafe', 'Café'), ('halal', 'Halal'), ('bbq_and_grills', 'BBQ & Grills'), ('', 'Other')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='restaurants/default.jpg', null=True, upload_to='restaurants/'),
        ),
    ]
