# Generated by Django 5.1.5 on 2025-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_restaurant_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddField(
            model_name='menuitemcategory',
            name='menu_item',
            field=models.ManyToManyField(related_name='categories', to='api.menuitem'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[(None, '----------'), ('fine_dining', 'Fine Dining'), ('vegan', 'Vegan'), ('seafood', 'Seafood'), ('fast_food', 'Fast Food'), ('drink_and_beverages', 'Drinks & Beverages'), ('desserts', 'Desserts'), ('cafe', 'Café'), ('halal', 'Halal'), ('bbq_and_grills', 'BBQ & Grills'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('', 'Other')], default='', max_length=25),
        ),
    ]
