# Generated by Django 5.1.5 on 2025-03-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_menuitem_category_menuitemcategory_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemcategory',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='menu_items', to='api.menuitemcategory'),
        ),
    ]
