# Generated by Django 5.1.5 on 2025-03-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_menuitemcategory_menu_item_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='MenuItemCategory',
        ),
    ]
