# Generated by Django 5.1.5 on 2025-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_menuitemmodifier_menuitemmodifierchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, default='menu_items/default.png', null=True, upload_to='side_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_items', models.ManyToManyField(related_name='addons', to='api.menuitem')),
            ],
        ),
    ]
