# Generated by Django 5.1.5 on 2025-04-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_menusideitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItemModifierChoice',
            new_name='OrderItemModifierChoice',
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='api.orderitem')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitemmodifierchoice',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.orderitemmodifier'),
        ),
        migrations.DeleteModel(
            name='MenuItemModifier',
        ),
    ]
