# Generated by Django 5.1.5 on 2025-04-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_sideitem_delete_menusideitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideitem',
            name='order_items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='side_items',
            field=models.ManyToManyField(related_name='order_items', to='api.sideitem'),
        ),
        migrations.RenameModel(
            old_name='OrderItemModifierChoice',
            new_name='MenuItemModifierChoice',
        ),
        migrations.CreateModel(
            name='MenuItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='api.menuitem')),
            ],
        ),
        migrations.AlterField(
            model_name='menuitemmodifierchoice',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.menuitemmodifier'),
        ),
        migrations.DeleteModel(
            name='OrderItemModifier',
        ),
    ]
