# Generated by Django 5.1.5 on 2025-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_sideitem_order_items_orderitem_side_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
