# Generated by Django 5.1.5 on 2025-04-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_orderitem_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideitem',
            name='image',
            field=models.ImageField(blank=True, default='side_items/default.jpg', null=True, upload_to='side_items/'),
        ),
    ]
