# Generated by Django 5.1.5 on 2025-04-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_sideitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='side_items',
        ),
        migrations.RemoveField(
            model_name='sideitem',
            name='quantity',
        ),
    ]
