# Generated by Django 5.1.5 on 2025-04-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_orderitemsideitem_orderitem_side_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='side_items', to='api.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitemcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('name', 'restaurant'), name='unique_menu_item_per_restaurant'),
        ),
    ]
