# Generated by Django 5.1.5 on 2025-04-28 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_sideitem_restaurant_alter_menuitemcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemmodifier',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_modifiers', to='api.restaurant'),
        ),
        migrations.AddConstraint(
            model_name='menuitemmodifier',
            constraint=models.UniqueConstraint(fields=('name', 'menu_item'), name='unique_modifier_per_menu_item'),
        ),
        migrations.AddConstraint(
            model_name='menuitemmodifierchoice',
            constraint=models.UniqueConstraint(fields=('label', 'modifier'), name='unique_label_per_modifier'),
        ),
    ]
