# Generated by Django 5.1.5 on 2025-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_menuitemmodifier_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemmodifier',
            name='is_multiselect',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
