# Generated by Django 5.1.5 on 2025-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_menuitemmodifier_is_multiselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_order_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menuitemmodifierchoice',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='sideitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
