# Generated by Django 5.1.5 on 2025-05-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='side_items',
        ),
        migrations.RemoveField(
            model_name='sideitem',
            name='restaurant',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='remark',
            new_name='special_instruction',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_side_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='api.menuitemmodifierchoice'),
        ),
        migrations.DeleteModel(
            name='OrderItemSideItem',
        ),
        migrations.DeleteModel(
            name='SideItem',
        ),
    ]
