# Generated by Django 5.1.5 on 2025-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_order_order_items_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='special_instruction',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
