# Generated by Django 5.1.5 on 2025-05-21 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
