# Generated by Django 5.1.5 on 2025-05-21 07:51

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Discount = apps.get_model("api", "Discount")
    for row in Discount.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])
    

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_discount_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid)
    ]
