# Generated by Django 5.1.5 on 2025-05-21 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20250521_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
