# Generated by Django 5.1.5 on 2025-05-21 09:32

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    MenuItem = apps.get_model("api", "MenuItem")
    for row in MenuItem.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])
        

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_menuitem_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid)
    ]
