# Generated by Django 5.1.5 on 2025-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('fine_dining', 'Fine Dining'), ('vegan', 'Vegan'), ('seafood', 'Seafood'), ('fast_food', 'Fast Food'), ('drink_and_beverages', 'Drinks & Beverages'), ('desserts', 'Desserts'), ('cafe', 'Café'), ('halal', 'Halal'), ('bbq_and_grills', 'BBQ & Grills'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('other', 'Other')], default='other', max_length=25),
        ),
    ]
