# Generated by Django 5.1.5 on 2025-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_discount_valid_from_alter_discount_valid_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurants/default.jpg', null=True, upload_to='restaurants/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
