# Generated by Django 5.1.5 on 2025-09-27 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_restaurant_image_alter_restaurant_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemcategory',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
