# Generated by Django 5.1.5 on 2025-09-27 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_menuitemcategory_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcategory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
